Feat 28 coordinates
AllenNeuralDynamics/aind-metadata-entry-js pull request #36
Opened 2022-10-26 18:26 UTC by mekhlakapoor

Customizes UI of coordinate fields in ephys session schema using UISchema and ObjectFieldTemplate. For now, the conditional for the uiSchema is in RenderForm.js itself, but can make a function uiSchemaSelection in SchemaHandlers.js once we have more than one uiSchema. Below pics are before/after 

![Screen Shot 2022-10-26 at 10 16 21 AM](https://user-images.githubusercontent.com/54870020/198105721-66f888d2-8ebc-4e58-ae54-8351131284f4.png)
![Screen Shot 2022-10-26 at 10 17 59 AM](https://user-images.githubusercontent.com/54870020/198105841-bf431625-78de-4b08-8b19-d90750fd95f2.png)

2022-10-26 18:27 UTC, dyf commented
@mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?

2022-10-26 18:34 UTC, jtyoung84 commented
> @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?

@dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.

2022-10-26 18:40 UTC, dyf commented
> > @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?
> 
> @dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.

Yeah, just not sure how to do that.  I think the desired UI behavior is 3 number entry boxes with inferred AP/ML/DV directions.  If that's not doable without creating a giant mess then this is fine IMO.

2022-10-26 18:54 UTC, jtyoung84 commented
> > > @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?
> > 
> > 
> > @dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.
> 
> Yeah, just not sure how to do that. I think the desired UI behavior is 3 number entry boxes with inferred AP/ML/DV directions. If that's not doable without creating a giant mess then this is fine IMO.

My worry is that the ui is already a hack around the schema listing these coordinates as enums. We can add another hack to set the default values to AP/DV/ML. I feel like we can avoid this by updating the schema to follow the geographical coordinates example here: https://json-schema.org/learn/miscellaneous-examples.html

This example renders as:

![Screenshot from 2022-10-26 11-52-45](https://user-images.githubusercontent.com/104453205/198111957-11410cbc-7db9-4a33-80d5-d8d65d8eac1b.png)

2022-10-26 20:54 UTC, mekhlakapoor commented
> > > > @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?
> > > 
> > > 
> > > @dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.
> > 
> > 
> > Yeah, just not sure how to do that. I think the desired UI behavior is 3 number entry boxes with inferred AP/ML/DV directions. If that's not doable without creating a giant mess then this is fine IMO.
> 
> My worry is that the ui is already a hack around the schema listing these coordinates as enums. We can add another hack to set the default values to AP/DV/ML. I feel like we can avoid this by updating the schema to follow the geographical coordinates example here: https://json-schema.org/learn/miscellaneous-examples.html
> 
> This example renders as:
> 
> ![Screenshot from 2022-10-26 11-52-45](https://user-images.githubusercontent.com/104453205/198111957-11410cbc-7db9-4a33-80d5-d8d65d8eac1b.png)

@dyf @jtyoung84  the ui-hack might be possible by using uiSchema's [enumDisabled](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#enumdisabled) feature and creating some hack to loop through and disable two directions per direction field and set a ui:placeholder for each) but it would definitely be pretty complicated for a UI task. 

For now, I can use [ui:description](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#description) to add a message stating to only do one of each, and I'm willing to help change the schema so that we can better assess which method (either ui-hack or schema change) would be better to meet this request.

2022-10-26 20:55 UTC, dyf commented
> > > > > @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?
> > > > 
> > > > 
> > > > @dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.
> > > 
> > > 
> > > Yeah, just not sure how to do that. I think the desired UI behavior is 3 number entry boxes with inferred AP/ML/DV directions. If that's not doable without creating a giant mess then this is fine IMO.
> > 
> > 
> > My worry is that the ui is already a hack around the schema listing these coordinates as enums. We can add another hack to set the default values to AP/DV/ML. I feel like we can avoid this by updating the schema to follow the geographical coordinates example here: https://json-schema.org/learn/miscellaneous-examples.html
> > This example renders as:
> > ![Screenshot from 2022-10-26 11-52-45](https://user-images.githubusercontent.com/104453205/198111957-11410cbc-7db9-4a33-80d5-d8d65d8eac1b.png)
> 
> @dyf @jtyoung84 the ui-hack might be possible by using uiSchema's [enumDisabled](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#enumdisabled) feature and creating some hack to loop through and disable two directions per direction field and set a ui:placeholder for each) but it would definitely be pretty complicated for a UI task.
> 
> For now, I can use [ui:description](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#description) to add a message stating to only do one of each, and I'm willing to help change the schema so that we can better assess which method (either ui-hack or schema change) would be better to meet this request.

Works for me!

2022-10-26 21:48 UTC, jtyoung84 commented
> > > > > > @mekhlakapoor how hard would it be to hard-code the "direction" values to be AP - DV - ML so that they don't need to be selected?
> > > > > 
> > > > > 
> > > > > @dyf Ideally that should be driven by the schema if the fields need to all be there to validate correctly.
> > > > 
> > > > 
> > > > Yeah, just not sure how to do that. I think the desired UI behavior is 3 number entry boxes with inferred AP/ML/DV directions. If that's not doable without creating a giant mess then this is fine IMO.
> > > 
> > > 
> > > My worry is that the ui is already a hack around the schema listing these coordinates as enums. We can add another hack to set the default values to AP/DV/ML. I feel like we can avoid this by updating the schema to follow the geographical coordinates example here: https://json-schema.org/learn/miscellaneous-examples.html
> > > This example renders as:
> > > ![Screenshot from 2022-10-26 11-52-45](https://user-images.githubusercontent.com/104453205/198111957-11410cbc-7db9-4a33-80d5-d8d65d8eac1b.png)
> > 
> > 
> > @dyf @jtyoung84 the ui-hack might be possible by using uiSchema's [enumDisabled](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#enumdisabled) feature and creating some hack to loop through and disable two directions per direction field and set a ui:placeholder for each) but it would definitely be pretty complicated for a UI task.
> > For now, I can use [ui:description](https://react-jsonschema-form.readthedocs.io/en/docs/api-reference/uiSchema/#description) to add a message stating to only do one of each, and I'm willing to help change the schema so that we can better assess which method (either ui-hack or schema change) would be better to meet this request.
> 
> Works for me!

If it's an easy fix, then go for it. I still don't think it's a sustainable idea to hack the ui to render a field to be something else instead of altering the underlying schema just to be that something else to begin with.

2022-10-31 17:24 UTC, jtyoung84 commented on src/components/RenderForm.js
> +}
Add newline

2022-10-31 17:26 UTC, jtyoung84 requested changes
A few new line issues need to be addressed

2022-10-31 18:33 UTC, jtyoung84 approved these changes

2022-10-31 18:35 UTC, merged