Feat 62 time selection
AllenNeuralDynamics/aind-metadata-entry-js pull request #65
Opened 2023-04-12 16:43 UTC by mekhlakapoor

closes #62 

Upgrades @rjsf/core package to latest version because time widget is only available after 5.0x 
Also updates validator compatible with new version, and removes 2020draft check (no longer in schemas)

2023-04-12 16:44 UTC, mekhlakapoor commented
<img width="1481" alt="Screen Shot 2023-04-12 at 9 44 21 AM" src="https://user-images.githubusercontent.com/54870020/231525899-e2de2060-4f11-4f5b-9c94-18f637b22cfa.png">
This is what time selection looks like when the clock widget is clicked

2023-04-12 22:56 UTC, jtyoung84 requested changes
I think some of the fields need second resolution

2023-04-13 22:23 UTC, mekhlakapoor commented
![Screen Shot 2023-04-13 at 3 15 12 PM](https://user-images.githubusercontent.com/54870020/231895991-28a434ca-a869-441b-9c3a-42c68ad29e00.png)

update: created a custom time widget that allows selection of hour, minute, second fields for all time format fields

2023-04-13 22:49 UTC, jtyoung84 approved these changes

2023-04-14 16:40 UTC, merged